// starters/nuxt-pinia-tailwind/pages/index.vue
<template>
  <div class="flex flex-col justify-center items-center mt-5">
    <header class="bg-blue-600 w-3/5 p-4 text-center rounded mb-5">
      <h1 class="text-2xl font-bold text-white">
        Nuxt, Pinia and TailwindCSS Starter kit
      </h1>
    </header>

    <NuxtLink to="/counter" class="text-lg text-blue-600 underline">
      See Counter example component
    </NuxtLink>

    <NuxtLink to="/api-example" class="text-lg text-blue-600 underline">
      See Fetch API example component
    </NuxtLink>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  name: 'IndexPage',
})
</script>

// starters/next-react-query-tailwind/src/pages/index.tsx
import type { NextPage } from 'next';
import Head from 'next/head';
import { Fragment } from 'react';
import { NavigationLink } from 'src/components';

const Home: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>next-react-query-tailwind starter kit</title>
        <meta name="description" content="Generated using starter.dev" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="w-3/5 my-5 mx-auto text-center">
        <h1 className="bg-blue-600 text-white text-2xl font-semibold p-4 rounded">
          Create Next app with React Query and Tailwind
        </h1>
        <ul>
          <li className="my-2.5">
            <NavigationLink to="/counter-example" label="See Counter example component" />
          </li>
          <li className="my-2.5">
            <NavigationLink to="/fetch-example" label="See Fetch example component" />
          </li>
        </ul>
      </header>
    </Fragment>
  );
};

export default Home;
