// starters/angular-apollo-tailwind/src/app/counter-example/counter-example.component.ts
import { Component } from '@angular/core';
import { counterVar } from './cache';

@Component({
    selector: 'app-counter-example',
    templateUrl: './counter-example.component.html',
    styleUrls: ['./counter-example.component.scss'],
})
export class CounterExampleComponent {
    get counter() {
        return counterVar();
    }

    increaseCounter() {
        counterVar(counterVar() + 1);
    }

    decreaseCounter() {
        counterVar(counterVar() - 1);
    }

    resetCounter() {
        counterVar(0);
    }
}

<div class="text-center">
    <div class="mx-10 mt-10 border-b-4 border-blue-700">
        <h1 class="text-3xl py-6">
            Increment, Decrement and Reset Button Example
        </h1>
    </div>
    <div class="flex flex-col mt-4 gap-2">
        <div class="flex flex-row gap-2 justify-center">
            <p class="py-2">
                Count: <span class="counter"> {{ counter }} </span>
            </p>
            <button
                class="bg-blue-700 hover:bg-blue-800 text-white font-bold py-2 px-4 rounded-lg"
                (click)="increaseCounter()"
            >
                Increment
            </button>
            <button
                class="bg-blue-700 hover:bg-blue-800 text-white font-bold py-2 px-4 rounded-lg"
                (click)="decreaseCounter()"
            >
                Decrement
            </button>
            <button
                class="bg-blue-700 hover:bg-blue-800 text-white font-bold py-2 px-4 rounded-lg"
                (click)="resetCounter()"
            >
                Reset
            </button>
        </div>
        <a href="/" class="underline text-blue-700"> Return Home </a>
    </div>
</div>

// starters/nuxt2-pinia-tailwind/components/CounterExample/CounterExample.vue
<template>
  <div class="flex flex-col justify-center items-center gap-5 mt-10">
    <header class="border-b-4 border-blue-600 w-3/5 pb-4 text-center">
      <h1 class="text-4xl font-bold">
        Increment, Decrement and Reset Button Examples
      </h1>
    </header>

    <div class="flex gap-20 justify-center items-center">
      <p class="text-2xl font-bold" data-testid="count-value">
        Count:{{ counterState.counter }}
      </p>

      <button
        class="text-white text-lg bg-blue-500 font-bold hover:bg-blue-700 rounded py-1 px-3"
        data-testid="increase-button"
        @click="increaseCount"
      >
        Increment
      </button>

      <button
        class="text-white text-lg bg-blue-500 font-bold hover:bg-blue-700 rounded py-1 px-3"
        data-testid="decrease-button"
        @click="decreaseCount"
      >
        Decrement
      </button>

      <button
        class="text-white text-lg bg-blue-500 font-bold hover:bg-blue-700 rounded py-1 px-3"
        data-testid="reset-button"
        @click="resetCount"
      >
        Reset
      </button>
    </div>
    <NuxtLink
      to="/"
      class="text-lg text-blue-600 underline hover:text-blue-400"
    >
      Return Home
    </NuxtLink>
  </div>
</template>

<script lang="ts">
import { defineComponent } from '@nuxtjs/composition-api';
import { useCounterStore } from '~/store/counterStore';

export default defineComponent({
  name: 'CounterExample',
  setup() {
    const counterState = useCounterStore();

    const increaseCount = () => {
      counterState.counter++;
    };

    const decreaseCount = () => {
      if (counterState.counter) {
        counterState.counter--;
      }
    };

    const resetCount = counterState.$reset.bind(counterState);
    
    return { counterState, increaseCount, decreaseCount, resetCount };
  },
});
</script>
