// starters/next-react-query-tailwind/src/components/Greeting/Greeting.tsx
import { useQuery } from "react-query";

export function Greeting() {
  const {
    data: message,
    isLoading,
    error,
  } = useQuery<string>('hello', async () => {
    return await fetch('https://api.starter.dev/hello?greeting=from This Dot Labs!').then((res) =>
      res.text()
    );
  });

  return (
    <div className="flex w-full text-xl justify-center">
      <div className="mr-[1em]">Message:</div>
      <div className={`text-left ${isLoading ? 'grow animate-pulse bg-gray-200 rounded-md' : 'grow-0'}`} role="display-message">
        { message }
      </div>
    </div>
  );  
}

// starters/solidjs-tailwind/src/components/FetchExample/Greeting.jsx
import { createResource } from 'solid-js';
import { useLocation } from '@solidjs/router';
import greetingFetcher from './greetingFetcher';

const Greeting = () => {
  const location = useLocation();

  const [resp] = createResource(() =>
    greetingFetcher(location.query?.greeting ?? '')
  );

  return (
    <div class="w-1/4 mx-auto">
      {resp.error ? (
        <div
          class="grow rounded border border-solid border-red-300 bg-red-100 p-4 text-center text-red-500"
          role="error-message"
        >
          Error:{' '}
          <span class="text-red-500">
            There was an error loading your greeting :(
          </span>
        </div>
      ) : (
        <div class="flex w-full justify-center text-xl">
          {resp.loading ? (
            <div class="grow animate-pulse rounded-md bg-gray-200 text-left">
              Loading...
            </div>
          ) : (
            <>
              <div class="mr-4">Message:</div>
              <div class="text-left" role="display-message">
                {resp()} from This Dot Labs!
              </div>
            </>
          )}
        </div>
      )}
    </div>
  );
};

export default Greeting;
