// starters/next-react-query-tailwind/src/pages/counter-example/index.tsx
import Link from "next/link";
import type { NextPage } from 'next';
import { Counter } from "src/components";
import { ReturnHome } from "src/components";

const CounterExample: NextPage = () => {
  return (
    <div className="w-3/5 my-5 mx-auto text-center">
      <h1 className="text-[2rem] font-bold border-b-4 border-blue-600 py-4 my-5">
        Increment, Decrement and Reset Button Example
      </h1>
      <div className="py-5">
        <Counter />
      </div>       
      <div className="my-2.5">
        <ReturnHome />
      </div>
    </div>
  );
}

export default CounterExample;

// starters/qwik-graphql-tailwind/src/routes/counter-example/index.tsx
import { component$ } from '@builder.io/qwik';
import Counter from '~/components/counter';

export default component$(() => {
  return (
    <div class="w-3/5 mx-auto text-center">
      <h1 class="text-[2rem] font-bold border-b-4 border-blue-600 py-4 my-5">
        Increment, Decrement and Reset Button Example
      </h1>
      <div class="py-5">
        <Counter />
      </div>
    </div>
  );
});
