// starters/next-react-query-tailwind/src/components/Counter/Counter.tsx
import { useState } from 'react';

const DEFAUT_COUNT = 0;

export function Counter() {
  const [count, setCount] = useState(0);

  return (
    <div className="flex justify-evenly whitespace-nowrap">
      <h2 className="text-2xl font-bold" role="display-element">Count: { count }</h2>
      <button onClick={() => setCount(count + 1)} role="button-increment">Increment</button>
      <button onClick={() => setCount(count - 1)} role="button-decrement">Decrement</button>
      <button onClick={() => setCount(DEFAUT_COUNT)} role="button-reset">Reset</button>
    </div>
  );
}

// starters/qwik-graphql-tailwind/src/components/counter/counter.tsx
import { component$, $, useStore } from '@builder.io/qwik';
import { Button } from '../../components/button/button';

export const Counter = component$(() => {
  const store = useStore({
    count: 0,
  });

  const increment$ = $(() => {
    store.count++;
  });

  const decrement$ = $(() => {
    store.count--;
  });

  const reset$ = $(() => {
    store.count = 0;
  });

  return (
    <div class="flex justify-evenly whitespace-nowrap">
      <Display store={store} />
      <Button title="Increment" action$={increment$} />
      <Button title="Decrement" action$={decrement$} />
      <Button title="Reset" action$={reset$} />
    </div>
  );
});

export const Display = component$((props: { store: { count: number } }) => {
  return (
    <h2 class="text-2xl font-bold" role="display-element">
      Count: {props.store.count}
    </h2>
  );
});
