// starters/nuxt3-pinia-vuetify/components/FetchExample/FetchExample.vue
<template>
	<div
		class="fetch-example-box d-flex flex-column justify-center align-center mt-5"
	>
		<div
			class="fetch-example-box__header border-b-4 border-blue-600 mb-4 text-center"
		>
			<h4 class="text-h5 font-weight-bold">Fetch Data From API</h4>
		</div>

		<div class="d-flex flex-row justify-center align-center mt-5 mb-10 text-h6">
			<p>Message:</p>
			<p class="ml-5 font-weight-bold" data-testid="message-value">
				{{ message }}
			</p>
		</div>
	</div>
</template>

<script lang="ts" setup>
const message = ref('loading...');

try {
	const { data } = await useFetch<string>(
		'https://api.starter.dev/hello?greeting=from This Dot Labs!'
	);
	message.value = data.value ?? 'Failed to fetch';
} catch (e) {
	message.value = 'Failed to fetch';
}
</script>

<style lang="scss" scoped>
.fetch-example-box {
	&__header {
		border-bottom: 4px solid rgb(var(--v-theme-primary));
	}
}
</style>

// starters/cra-rxjs-styled-components/src/components/Fetch-Example/Fetch-Example.tsx
import {
  FetchExampleContainer,
  HeaderContainer,
  Header,
  HomeLinkDiv,
  ReturnHomeLink,
  Message,
} from './Fetch-Example.styles';
import { useState, useEffect } from 'react';
import { fromFetch } from 'rxjs/fetch';

export const FetchExample = () => {
  const [message, setMessage] = useState<string>('');
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    const subscription = fromFetch(
      'https://api.starter.dev/hello?greeting=from This Dot Labs!'
    ).subscribe((response) => response.text().then((data) => setMessage(data)));
    setLoading(false);
    return () => subscription.unsubscribe();
  }, []);

  return (
    <FetchExampleContainer>
      <HeaderContainer>
        <Header>RxJS Fetch Data from API</Header>
      </HeaderContainer>
      <Message>Message: {loading ? '...Loading message' : message}</Message>
      <HomeLinkDiv>
        <ReturnHomeLink to="/">Return Home</ReturnHomeLink>
      </HomeLinkDiv>
    </FetchExampleContainer>
  );
};
