// starters/next-react-query-tailwind/src/pages/counter-example/index.tsx
import Link from "next/link";
import type { NextPage } from 'next';
import { Counter } from "src/components";
import { ReturnHome } from "src/components";

const CounterExample: NextPage = () => {
  return (
    <div className="w-3/5 my-5 mx-auto text-center">
      <h1 className="text-[2rem] font-bold border-b-4 border-blue-600 py-4 my-5">
        Increment, Decrement and Reset Button Example
      </h1>
      <div className="py-5">
        <Counter />
      </div>       
      <div className="my-2.5">
        <ReturnHome />
      </div>
    </div>
  );
}

export default CounterExample;

// starters/vue3-apollo-quasar/src/pages/CounterExample.vue
<template>
  <q-page class="row items-center column">
    <h4 class="text-center">Increment, Decrement and Reset Button Example</h4>
    <q-separator color="primary" size="4px" />
    <NumberCounter />
  </q-page>
  <div></div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'CounterExample',
});
</script>

<script lang="ts" setup>
import { NumberCounter } from 'src/components';
</script>
