// starters/next-react-query-tailwind/.storybook/preview.js
import '../src/styles/globals.css';
import { ModuleMocker } from 'jest-mock';
import { addDecorator } from '@storybook/react';
import { initialize, mswDecorator } from 'msw-storybook-addon';
import { RouterContext } from 'next/dist/shared/lib/router-context';

initialize();
addDecorator(mswDecorator);

window.jest = new ModuleMocker(window);

export const parameters = {
  actions: { argTypesRegex: '^on[A-Z].*' },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
  nextRouter: {
    Provider: RouterContext.Provider,
  },
};

// starters/solidjs-tailwind/.storybook/preview.js
import '../src/index.css';
import { render } from 'solid-js/web';

export const decorators = [
  (Story) => {
    const solidRoot = document.createElement('div');

    render(Story, solidRoot);

    return solidRoot;
  },
];

export const parameters = {
  actions: { argTypesRegex: '^on[A-Z].*' },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
};
