// starters/qwik-fetch-tailwind/src/routes/counter/counter.tsx
import { component$, $, useStore } from '@builder.io/qwik';
import { Button } from '../../components/button/button';
import * as styles from './counter.classNames';

export const Counter = component$(() => {
  const store = useStore({
    count: 0,
  });

  const increment$ = $(() => store.count++);
  const decrement$ = $(() => store.count--);
  const reset$ = $(() => (store.count = 0));

  return (
    <div className={styles.container}>
      <Display store={store} />
      <Button title="-" action$={decrement$} />
      <Button title="+" action$={increment$} />
      <Button title="&times;" action$={reset$} />
    </div>
  );
});

export const Display = component$((props: { store: { count: number } }) => {
  return (
    <div className={styles.textContainer}>
      <p className={styles.h3Text}>Count:</p> <h1 className={styles.h1Text}>{props.store.count}</h1>
    </div>
  );
});

// starters/remix-gql-tailwind/app/components/Counter/Counter.tsx
import { useState } from 'react';
import { Button } from './Button';
import * as styles from './Counter.classNames'


export const Counter = () => {
  const [count, setCount] = useState(0);

  const incrementCount = () => {
    setCount(count + 1);
  };

  const decrementCount = () => {
    if (count !== 0) setCount(count - 1);
  };

  return (
    <div className={styles.container}>
      <div>
        <div className={styles.textContainer}>
          <p className={styles.h3Text}>Count:</p>
          <h1 className={styles.h1Text}>{count}</h1>
        </div>
        <div>
          <Button title={"-"} action={decrementCount} />
          <Button title={"+"} action={incrementCount} />
        </div>
      </div>
    </div>
  );
}
