// starters/angular-apollo-tailwind/src/app/fetch-example/fetch-example.component.ts
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { HelloService } from './hello.service';

@Component({
  selector: 'app-fetch-example',
  templateUrl: './fetch-example.component.html',
  styleUrls: ['./fetch-example.component.scss']
})
export class FetchExampleComponent implements OnInit {

  private message: string = 'angular-apollo-tailwind starter.dev!'
  helloMessage$!: Observable<any>;

  constructor(
    private helloService: HelloService
  ) { }

  ngOnInit(): void {
    this.helloMessage$ = this.helloService.getHelloMessage(this.message)
  }

}

<div class="w-2/5 my-5 mx-auto text-center">
    <h1 class="text-[2rem] font-bold border-b-4 border-blue-600 py-4 my-5">
        Apollo Fetch Data From API
    </h1>
    <div class="flex w-full text-xl justify-center">
        <div class="mr-[1em]">Message:</div>
        <div
            class="text-left"
            [ngClass]="{
                'grow animate-pulse bg-gray-200 rounded-md':
                    greetingMessageLoading,
                'grow-0': !greetingMessageLoading
            }"
        >
            {{ greetingMessage$ | async }}
        </div>
    </div>
    <div class="my-2.5">
        <a href="/" class="underline text-blue-600 hover:text-blue-800 text-xl">
            Return Home
        </a>
    </div>
</div>

// starters/nuxt-bridge-pinia-tailwind/components/FetchExample/FetchExample.vue
<template>
  <div
    class="flex flex-col justify-center items-center gap-5 mt-10 w-3/5 mx-auto"
  >
    <header class="border-b-4 border-blue-600 w-3/5 pb-4 text-center">
      <h1 class="text-4xl font-bold">Fetch Data from API</h1>
    </header>

    <div class="flex gap-4 justify-center items-center text-2xl">
      <p>Message:</p>
      <p
        :class="{
          'grow-0': data,
          'grow animate-pulse bg-gray-200 rounded-md w-40 h-6': !data,
        }"
        :data-testid="data ? 'message-value' : 'message-skeleton'"
      >
        {{ data }}
      </p>
    </div>
    <NuxtLink
      to="/"
      class="text-lg text-blue-600 underline hover:text-blue-400"
    >
      Return Home
    </NuxtLink>
  </div>
</template>

<script lang="ts">
import { useLazyAsyncData } from '#imports'

export default {
  name: 'FetchExample',
  setup() {
    const encodedMessage = encodeURIComponent('from this Dot Labs!')

    const { data, error } = useLazyAsyncData<string>('message', () =>
      $fetch(
        `https://api.starter.dev/.netlify/functions/server/hello?greeting=${encodedMessage}`
      )
    )

    if (error.value) {
      data.value = 'Error fetching data'
    }

    return { data }
  },
}
</script>
