// starters/qwik-fetch-tailwind/src/routes/counter/index.tsx
import { component$, useStore } from '@builder.io/qwik';
import { Link } from '@builder.io/qwik-city';

export default component$(() => {
  const store = useStore({
    count: 0,
  });

  return (
    <div>
      <h1>Increment, Decrement and Reset Button Examples</h1>
      <Display store={store} />
      <button onClick$={() => store.count++}>Increment</button>
      <button onClick$={() => store.count--}>Decrement</button>
      <button onClick$={() => (store.count = 0)}>Reset</button>
      <Link href="/">Return Home</Link>
    </div>
  );
});

export const Display = component$((props: { store: { count: number } }) => {
  return <div>Count: {props.store.count}</div>;
});

// starters/cra-rxjs-styled-components/src/components/Counter/Counter.tsx
import { useState } from 'react';
import {
  CounterButton,
  Header,
  CounterContainer,
  CounterButtonContainer,
  CurrentCountText,
  ReturnHomeLink,
  HomeLinkDiv,
} from './Counter.styles';

export function Counter() {
  const [count, setCount] = useState(0);

  return (
    <CounterContainer>
      <Header>Increment, Decrement and Reset Button Examples</Header>

      <CounterButtonContainer>
        <CurrentCountText>Count:{count}</CurrentCountText>
        <CounterButton onClick={() => setCount(count + 1)}>
          Increment
        </CounterButton>
        <CounterButton onClick={() => setCount(count - 1)}>
          Decrement
        </CounterButton>
        <CounterButton onClick={() => setCount(0)}>Reset</CounterButton>
      </CounterButtonContainer>
      <HomeLinkDiv>
        <ReturnHomeLink to="/">Return Home</ReturnHomeLink>
      </HomeLinkDiv>
    </CounterContainer>
  );
}
