// starters/next-react-query-tailwind/src/components/Counter/Counter.tsx
import { useState } from 'react';

const DEFAUT_COUNT = 0;

export function Counter() {
  const [count, setCount] = useState(0);

  return (
    <div className="flex justify-evenly whitespace-nowrap">
      <h2 className="text-2xl font-bold" role="display-element">Count: { count }</h2>
      <button onClick={() => setCount(count + 1)} role="button-increment">Increment</button>
      <button onClick={() => setCount(count - 1)} role="button-decrement">Decrement</button>
      <button onClick={() => setCount(DEFAUT_COUNT)} role="button-reset">Reset</button>
    </div>
  );
}

// starters/solidstart-tanstackquery-tailwind-modules/src/components/Counter.tsx
import { createSignal } from "solid-js";

export default function Counter() {
  const [count, setCount] = createSignal(0);
  return (
    <div class="flex flex-wrap lg:flex-nowrap justify-center gap-14 items-center">
      <strong role="display-count" class="text-xl">
        Count: {count()}
      </strong>
    <button
    type="button"
    class="bg-blue-500 text-white text-base font-medium px-4 py-2 rounded-md outline-none"
    onClick={() => setCount(count() + 1)}>
      Increment
    </button>
    <button
    type="button"
    class="bg-blue-500 text-white text-base font-medium px-4 py-2 rounded-md outline-none"
    onClick={() => setCount(count() - 1)}>
      Decrement
    </button>
    <button
    type="button"
    class="bg-blue-500 text-white text-base font-medium px-4 py-2 rounded-md outline-none"
    onClick={() => setCount(0)}>
      Reset
    </button>
    </div>
  );
}
