// starters/next12-react-query-tailwind/src/pages/index.tsx
import type { NextPage } from 'next';
import Head from 'next/head';
import { Fragment } from 'react';
import { NavigationLink } from 'src/components';

const Home: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>next12-react-query-tailwind starter kit</title>
        <meta name="description" content="Generated using starter.dev" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="w-3/5 my-5 mx-auto text-center">
        <h1 className="bg-blue-600 text-white text-2xl font-semibold p-4 rounded">
          Create Next app with React Query and Tailwind
        </h1>
        <ul>
          <li className="my-2.5">
            <NavigationLink
              to="/counter-example"
              label="See Counter example component"
            />
          </li>
          <li className="my-2.5">
            <NavigationLink
              to="/fetch-example"
              label="See Fetch example component"
            />
          </li>
        </ul>
      </header>
    </Fragment>
  );
};

export default Home;

// starters/nuxt3-pinia-vuetify/pages/index.vue
<script setup lang="ts">
useHead({
	title: 'Nuxt 3, Pinia and Vuetify',
	meta: [
		{
			name: 'Nuxt 3, Pinia and Vuetify',
			content: 'Nuxt 3, Pinia and Vuetify kit',
		},
	],
});
</script>

<template>
	<main class="w-50">
		<header class="bg-blue-darken-2 pa-4 text-center rounded mb-5">
			<h2 class="font-weight-bold text-white">
				Nuxt 3, Pinia and Vuetify Starter kit
			</h2>
		</header>
		<div class="d-flex flex-column justify-center align-center mt-4">
			<NuxtLink to="/counter" class="text-subtitle-1 text-blue-darken-2">
				See Counter example component
			</NuxtLink>
			<NuxtLink to="/greet" class="text-subtitle-1 text-blue-darken-2 mt-2">
				See Fetch example component
			</NuxtLink>
		</div>
	</main>
</template>
