// starters/qwik-fetch-tailwind/src/components/button/button.tsx
import { component$, PropFunction } from '@builder.io/qwik';
import * as styles from './button.classNames';

interface ButtonProps {
  action$: PropFunction<() => void>;
  title: string;
}

export const Button = component$((props: ButtonProps) => {
  return (
    <button className={styles.button} onClick$={props.action$}>
      {props.title}
    </button>
  );
});

// starters/expo-zustand-styled-components/src/components/Button/Button.tsx
import React from 'react';
import { TouchableOpacityStyled, TextStyled } from './Button.styles';

interface ButtonProps {
  title: string;
  onPress: () => void;
}

const Button = ({ title, onPress }: ButtonProps) => {
  return (
    <TouchableOpacityStyled onPress={onPress}>
      <TextStyled>{title}</TextStyled>
    </TouchableOpacityStyled>
  );
};

export default Button;
